export enum apiRoutes {
  LOGIN = '/auth/login',
  SIGNUP = '/auth/register',
  SIGNOUT = '/auth/signout',
  REFRESH_TOKENS = '/auth/refresh',
  FETCH_UPORABNIK = '/auth',
  FETCH_UPORABNIKI = '/users',
  UPORABNIKI_PREFIX = '/users',
  UPLOAD_AVATAR_IMAGE = '/users/upload',
  UPLOAD_PRODUCT_IMAGE = '/products/upload',
  PRODUCTS_PREFIX = '/products',
  ROLES_PREFIX = '/roles',
  ORDERS_PREFIX = '/orders',
  PERMISSIONS_PREFIX = '/permissions',
}
